version: '3'

services:
  eventeum:
    image: eventeum/eventeum:latest
    ports:
    - "8060:8060"
    depends_on:
      - mongodb
      - kafka
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_URL: http://172.16.4.104:22001
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:9092
    networks:
    - default

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - $HOME/mongodb/data/db:/data/db
    networks:
    - default

  zookeeper:
    image: confluent/zookeeper
    ports:
    - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  rabbitmq:
    image: rabbitmq:3.6.14-management
    ports:
    - "5672:5672"
    networks:
    - default